### ISSUE TITLE
Issue while deployment

### ISSUE THREAD

**Issue by FuckingToasters** [TykTechnologies/tyk-gateway-docker#72]
Helo, so i constantly get following issue and i don't understand how i can resolve this, i found multiple tyk gateway images but all of them caused the same issue.

```
29.18MB/29.18MB c4de4ae193fe Pull complete tyk-gateway Pulled Container tyk-gateway-tyk-redis-1 Creating Container tyk-gateway-tyk-redis-1 Created Container tyk-gateway-tyk-gateway-1 Creating Container tyk-gateway-tyk-gateway-1 Created Container tyk-gateway-tyk-redis-1 Starting Container tyk-gateway-tyk-redis-1 Started Container tyk-gateway-tyk-gateway-1 Starting Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/data/compose/41/tyk.standalone.conf" to rootfs at "/opt/tyk-gateway/tyk.conf": mount /data/compose/41/tyk.standalone.conf:/opt/tyk-gateway/tyk.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type 
```

here my compose file:
```yml
version: '3.0'
services:
  tyk-gateway:
    image: tykio/tyk-gateway:v4.1.0
    #ports:
      #- 8080:8080
    networks:
      webproxy:
        ipv4_address: 172.26.0.17
    volumes:
      - ./tyk.standalone.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./certs:/opt/tyk-gateway/certs
    environment:
      - TYK_GW_SECRET=foo
    depends_on:
      - tyk-redis
      
  tyk-redis:
    image: redis:6.2.7-alpine
    networks:
      webproxy:
        ipv4_address: 172.26.0.205
    #ports:
      #- 6379:6379

networks:
  webproxy:
    driver: bridge
    external: true
    ```
